#!/bin/sh

RCol='\e[0m'    # Text Reset
Gre='\e[0;32m';
BGre='\e[1;32m';

say () {
  printf "$1\n"
}

say "${Gre}Clean project${Gre}"

say "Delete .git/"         && \
rm -rf .git/               && \
say "Delete .github-todos" &&\
rm .github-todos           && \
say "Delete README.md"     && \
rm README.md               && \
say "Delete License.md"    && \
rm License.md              && \
say "Delete tmp.shell"     && \
rm tmp                     && \
say "Delete init.shell"    && \
rm init                    && \

say ${PWD##*/}

say "${BGre}Sucessfully clean"

